### ISSUE TITLE
Hi

### ISSUE THREAD

**Issue by Cyb3rC3lt** [a-fakhri/a-fakhri.github.io#1]
Apologies for the random issue but I know of no other way to get in touch. I found this comment of yours which was very insightful.

https://github.com/nrandecker/particle/issues/37

I have that theme running fine but I'd like to make the main background color red. I just branched the original code and don't have anything running locally. Can jeckyl be added to github to recompile the assets online with a new background colour or do we need do all the things mentioned in the "run locally" text? Also any idea which file the change should go into please?

I'd ask the author but he's made the repository archived.

Thanks a lot

**Comment by a-fakhri** [comment]
Hey, no worries. I don't think there is a way to compile it on gtihub, but I recall it was straightforward to compile the assets locally. Sorry, but it has been years since I made that comment, so I don't recall which file you have to change specifically.

**Comment by Cyb3rC3lt** [comment]
No problem at all and thanks for the reply. I managed to compile it locally with a bit of effort 😊
